baseURL = 'https://example.org/'
languageCode = 'cs'

pluralizeListTitles = false

title = 'Chytrý dávkovač pilulek'
theme= 'hello-friend'
homeSubtitle = "A simple and beautiful blog"

[params.logo]
    logoText = "ZPC"
    logoHomeLink = "/" 

[menu]  
    [[menu.main]]
        identifier = "ome"
        name       = "O mě"
        url        = "/ome"

    [[menu.main]]
        identifier = "blog"
        name       = "Blog"
        url        = "/Projekty"
        weight     = 2

    [[menu.main]]
        identifier = "Projekt"
        name       = "Projekt"
        url        = "/Projekt"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser.attribute]
      block = true
      title = true